### ISSUE TITLE
How to pass the test data through property file or .csv 

### ISSUE THREAD

**Issue by ChethanGKC** [aws-samples/aws-device-farm-appium-tests-for-sample-app#16]
Can any one please let me know how to pass the test data through property file or .csv in AWS Device farm.

**Comment by jzthinkgeek** [comment]
Hi, you can package your test data into the zip file and let your test read data.

**Comment by ChethanGKC** [comment]
@jzthinkgeek : thanks for the fast replay,  i placed my tests data in my zip file but what path i need to specify to read that ?

**Comment by ChethanGKC** [comment]
@jzthinkgeek i tried with path like this zip-with-dependencies/test-classes/android.properties but it's not working

**Comment by ChethanGKC** [comment]
![screen shot 2018-02-09 at 4 20 08 pm](https://user-images.githubusercontent.com/20571390/36024274-40372b4c-0db5-11e8-942c-c1ed6f79c9fe.png)
my zip file consists of above items showed in the screenshot. now i need to call the android.properties file for this which path i need to specify.

**Comment by ChethanGKC** [comment]
@jzthinkgeek : Thanks for the help. I fixed this issue by combining .property file with the test jar and calling that property file by using class loader.

Hence closing this issue
